# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d88264a82f7600a46c1c14ea037cc48d28818de1b395c1c0c2a27b13f6ac89532db3cf6d522ba173fe1a3fc7150119cc2617f9580a1c5b5f641a5b13da9e30a8

test:
  secret_key_base: a1436a6a3ef8f641f19ac513eda3b5172292a745c5ab1a81ae13a9b900aafab9b5db2f39600792f766c8a47668425fd1b3fc968a0a56874fd7fa452dc662e955

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
